FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nestjs -u 1001 && \
    mkdir -p dist && \
    chown -R nestjs:nodejs /usr/src/app && \
    chmod -R 755 /usr/src/app

USER nestjs

EXPOSE 3000
CMD ["npm", "run", "start:prod"]
