services:
  price-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: soprano_price_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    working_dir: /usr/src/app

  mongo:
    image: mongo:4.4
    container_name: soprano_price_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo:/data/db
